import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
group = "com.idli"
version = "0.0.1"
plugins {
    application
    idea
    kotlin("jvm") version "1.3.61"
}

repositories {
    mavenCentral()
}
application {
    mainClassName = "com.idli.AppKt"
}

dependencies {
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.0.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.4.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.4.2")
    implementation("mysql:mysql-connector-java:8.0.19")
    implementation(kotlin("stdlib-jdk8"))
    implementation("com.github.seratch:kotliquery:1.3.1")
    implementation(fileTree("libs"))

}

tasks.test {
    useJUnitPlatform()
}
val run: JavaExec by tasks
run.standardInput = System.`in`

val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.8"
}
val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "1.8"
}